version: '3.8'

services:
  nextjs-app:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DOCKER_DEVELOPMENT=true
    command: npm run dev
